domain: bhavyajagjananidarbar.org

tls:
  enabled: true
  secretName: bjjd-tls
  clusterIssuer: letsencrypt-prod

certManager:
  enabled: true
  email: s.gyanendra1@gmail.com
  clusterIssuer: letsencrypt-prod

services:
  vault:
    name: vault
    host: vault
    port: 8200

  jenkins:
    name: jenkins
    host: jenkins
    port: 9090

  keycloak:
    name: keycloak
    host: keycloak
    port: 8080

middlewares:
  auth:
    enabled: true
    secretName: basic-auth-secret

  rateLimit:
    average: 100
    burst: 50