controller:
  image: "docker.io/jenkins/jenkins:lts-jdk21"
  imagePullPolicy: Always
  adminUser: admin
  adminPassword: admin@9379

persistence:
  enabled: true
  size: 20Gi

service:
  type: ClusterIP
  port: 9090
