apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  serviceName: keycloak
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "start"
            - "--hostname-strict=false"
            - "--http-enabled=true"
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: "{{ .Values.postgres.host }}"
            - name: KC_DB_URL_PORT
              value: "{{ .Values.postgres.port }}"
            - name: KC_DB_URL_DATABASE
              value: "{{ .Values.postgres.dbName }}"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: password

            # Admin credentials
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: password
                  
          extraEnvVars:
            - name: KC_DB_URL_PARAMETERS
              value: "sslmode=disable"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https

          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 5

          resources:
{{ toYaml .Values.resources | indent 12 }}

  volumeClaimTemplates:
    - metadata:
        name: keycloak-data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
