apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
data:
  username: {{ .Values.admin.username | b64enc }}
  password: {{ .Values.admin.password | b64enc }}
