apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/bjjd/k8s-data/jenkins"
  persistentVolumeReclaimPolicy: Retain
