apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secrets
  namespace: data
type: Opaque
stringData:
  POSTGRES_SUPERUSER_PASSWORD: "bjjd_9379"
  KEYCLOAK_DB_PASSWORD: "keycloak@9379"
  USERS_DB_PASSWORD: "users@9379"
  PERSONS_DB_PASSWORD: "persons@9379"
  ACCOUNTS_DB_PASSWORD: "accounts@9379"
  DARSHAN_DB_PASSWORD: "darshan@9379"
  PROJECTS_DB_PASSWORD: "projects@9379"
