apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
  namespace: {{ .Release.Namespace }}
spec:
  rateLimit:
    average: {{ .Values.middlewares.rateLimit.average }}
    burst: {{ .Values.middlewares.rateLimit.burst }}